# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/iir2mc_clock.xdc

# XDC: imports/sysgen/iir2mc.xdc

# Block Designs: bd/iir2mc_bd/iir2mc_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iir2mc_bd || ORIG_REF_NAME==iir2mc_bd} -quiet] -quiet

# IP: bd/iir2mc_bd/ip/iir2mc_bd_iir2mc_1_0/iir2mc_bd_iir2mc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iir2mc_bd_iir2mc_1_0 || ORIG_REF_NAME==iir2mc_bd_iir2mc_1_0} -quiet] -quiet

# XDC: /xilinxworks/sysgen/notch_panda/netlist/ip/iir2mc/src/ip_catalog/iir2mc.gen/sources_1/bd/iir2mc_bd/iir2mc_bd_ooc.xdc
