# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /xilinxworks/sysgen/notch_panda/netlist/ip/iir2mc/src/ip_catalog/iir2mc.srcs/sources_1/bd/iir2mc_bd/ip/iir2mc_bd_iir2mc_1_0/iir2mc_bd_iir2mc_1_0.xci
# IP: The module: 'iir2mc_bd_iir2mc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /xilinxworks/sysgen/notch_panda/netlist/ip/iir2mc/src/ip_catalog/iir2mc.gen/sources_1/bd/iir2mc_bd/ip/iir2mc_bd_iir2mc_1_0/iir2mc_floating_point_v7_1_i0/iir2mc_floating_point_v7_1_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iir2mc_floating_point_v7_1_i0 || ORIG_REF_NAME==iir2mc_floating_point_v7_1_i0} -quiet] -quiet

# IP: /xilinxworks/sysgen/notch_panda/netlist/ip/iir2mc/src/ip_catalog/iir2mc.gen/sources_1/bd/iir2mc_bd/ip/iir2mc_bd_iir2mc_1_0/iir2mc_floating_point_v7_1_i1/iir2mc_floating_point_v7_1_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iir2mc_floating_point_v7_1_i1 || ORIG_REF_NAME==iir2mc_floating_point_v7_1_i1} -quiet] -quiet

# IP: /xilinxworks/sysgen/notch_panda/netlist/ip/iir2mc/src/ip_catalog/iir2mc.gen/sources_1/bd/iir2mc_bd/ip/iir2mc_bd_iir2mc_1_0/iir2mc_floating_point_v7_1_i2/iir2mc_floating_point_v7_1_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iir2mc_floating_point_v7_1_i2 || ORIG_REF_NAME==iir2mc_floating_point_v7_1_i2} -quiet] -quiet

# IP: /xilinxworks/sysgen/notch_panda/netlist/ip/iir2mc/src/ip_catalog/iir2mc.gen/sources_1/bd/iir2mc_bd/ip/iir2mc_bd_iir2mc_1_0/iir2mc_floating_point_v7_1_i3/iir2mc_floating_point_v7_1_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iir2mc_floating_point_v7_1_i3 || ORIG_REF_NAME==iir2mc_floating_point_v7_1_i3} -quiet] -quiet

# IP: /xilinxworks/sysgen/notch_panda/netlist/ip/iir2mc/src/ip_catalog/iir2mc.gen/sources_1/bd/iir2mc_bd/ip/iir2mc_bd_iir2mc_1_0/iir2mc_floating_point_v7_1_i4/iir2mc_floating_point_v7_1_i4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iir2mc_floating_point_v7_1_i4 || ORIG_REF_NAME==iir2mc_floating_point_v7_1_i4} -quiet] -quiet

# XDC: /xilinxworks/sysgen/notch_panda/netlist/ip/iir2mc/src/ip_catalog/iir2mc.gen/sources_1/bd/iir2mc_bd/ip/iir2mc_bd_iir2mc_1_0/constrs/iir2mc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iir2mc_bd_iir2mc_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /xilinxworks/sysgen/notch_panda/netlist/ip/iir2mc/src/ip_catalog/iir2mc.srcs/sources_1/bd/iir2mc_bd/ip/iir2mc_bd_iir2mc_1_0/iir2mc_bd_iir2mc_1_0.xci
# IP: The module: 'iir2mc_bd_iir2mc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /xilinxworks/sysgen/notch_panda/netlist/ip/iir2mc/src/ip_catalog/iir2mc.gen/sources_1/bd/iir2mc_bd/ip/iir2mc_bd_iir2mc_1_0/iir2mc_floating_point_v7_1_i0/iir2mc_floating_point_v7_1_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iir2mc_floating_point_v7_1_i0 || ORIG_REF_NAME==iir2mc_floating_point_v7_1_i0} -quiet] -quiet

# IP: /xilinxworks/sysgen/notch_panda/netlist/ip/iir2mc/src/ip_catalog/iir2mc.gen/sources_1/bd/iir2mc_bd/ip/iir2mc_bd_iir2mc_1_0/iir2mc_floating_point_v7_1_i1/iir2mc_floating_point_v7_1_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iir2mc_floating_point_v7_1_i1 || ORIG_REF_NAME==iir2mc_floating_point_v7_1_i1} -quiet] -quiet

# IP: /xilinxworks/sysgen/notch_panda/netlist/ip/iir2mc/src/ip_catalog/iir2mc.gen/sources_1/bd/iir2mc_bd/ip/iir2mc_bd_iir2mc_1_0/iir2mc_floating_point_v7_1_i2/iir2mc_floating_point_v7_1_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iir2mc_floating_point_v7_1_i2 || ORIG_REF_NAME==iir2mc_floating_point_v7_1_i2} -quiet] -quiet

# IP: /xilinxworks/sysgen/notch_panda/netlist/ip/iir2mc/src/ip_catalog/iir2mc.gen/sources_1/bd/iir2mc_bd/ip/iir2mc_bd_iir2mc_1_0/iir2mc_floating_point_v7_1_i3/iir2mc_floating_point_v7_1_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iir2mc_floating_point_v7_1_i3 || ORIG_REF_NAME==iir2mc_floating_point_v7_1_i3} -quiet] -quiet

# IP: /xilinxworks/sysgen/notch_panda/netlist/ip/iir2mc/src/ip_catalog/iir2mc.gen/sources_1/bd/iir2mc_bd/ip/iir2mc_bd_iir2mc_1_0/iir2mc_floating_point_v7_1_i4/iir2mc_floating_point_v7_1_i4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==iir2mc_floating_point_v7_1_i4 || ORIG_REF_NAME==iir2mc_floating_point_v7_1_i4} -quiet] -quiet

# XDC: /xilinxworks/sysgen/notch_panda/netlist/ip/iir2mc/src/ip_catalog/iir2mc.gen/sources_1/bd/iir2mc_bd/ip/iir2mc_bd_iir2mc_1_0/constrs/iir2mc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iir2mc_bd_iir2mc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
